### PR TITLE
Add close button to PNP iframe

### PR DESCRIPTION
**Pull request by Obihoernchen**

### CODE REVIEW

**Comment by stibi** [comment]
Hi there,
thanks very much…the close button is really missing there.
I'm wondering, is anybody taking care about the pull requests here?

At least I filled an issue for this: https://dev.icinga.org/issues/9797

**Comment by dnsmichi** [comment]
Hi,

we require users to open an issue on our redmine development tracker in order to help organize our development sprints and roadmaps. Although that's no promise that patches are automatically reviewed and merged - we all have lots of stuff to do, be it finishing icingaweb2 2.0.0 or working on icinga2 2.4.0. 

Thanks for contribution :)

**Comment by stibi** [comment]
Hi, sure, I understand, sorry if the I sounded bad here, I appreciate your work and thank you very much.

**Comment by monotek** [comment]
Applying these changes leads to second scrollbar.

**Comment by Thomas-Gelf** [comment]
Similar pull request has been merged into the [pnp](https://github.com/Icinga/icingaweb2-module-pnp/) module. Closing this one as the pnp4nagios module has been deprecated - pnp can be used as a fully compatible replacement, it's basically the same code.

**Pull request closed without merging**
